#cloud-config
users:
  - name: opsuser01
    sudo: False
    lock_passwd: True
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDjqJrOlAxbXPoevLKbCJJ2WSLX3ShSIRQyiWaT2+Y5/Ru8Ol+UxQwPunZ/gxZObpDEfvSBJ2Qu4fZ0tfqYZZb7hUUzTSRwIKMSgoSfF2SfccSTvYp1JUvT0NNxOrZ1dmPrLpWZzLUX1sgAo1JvsC7Ae0L8MgUvgyM42S3YSw5+YgQ8pu7dM2rL3bZXctHe6RjEj+uUsMmP3z9r1WrrSSO4xgkK+BRyqNyH/HaLD2SqWoEVYN8vjC138vGpMXXzPMKKGopsHhbtoUxTrwBibl5nRY0bTah0Mlwy8O6gkxpQjacTZfYrpoL0qr9qATXqxDsDbue3wy4BBmf8FY/GCHq2A8/7+6WK9eYC3zbSF2b1wQa+KeHx2N/icjK+bUTnbH0vKfR3MRS0ZGmu9nOPlcII64nmG55EYMyqiBOcIEUa1NPc1F1mPRa03G3+R6EywTRkj0S1tk8KLU4xuKEwtIDSJdO7717KBUB3c0s90BwPyGR8/0oGzFRgsNShykYBKa7VVsZYVlik2fQ5i3G3cGOhZT7YInfEOUQvMSLME+uvnQNgi8orTVAJXvGhP3jHOJy74Og+rc3MebnZ7G0PjzJwH5ToRxvWDz/lFiJNc4Re5sYfCfIxp4tGi7264V44K0eLQuoL/ffzPhXyYNc+/vOkl6TaZ4Qs0oCpfR8jJkKEeQ==
