apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cluster-baseline-settings
resources:
- namespace.yaml
- resource-quota.yaml
- limit-range.yaml
- rbac.yaml
- fim/fim-standin.yaml
- av/av-standin.yaml
- kured/kured.yaml
images:
- name: busybox
  newName: acraksxoopss4bpzbr6.azurecr.io/live/library/busybox
  newTag: 1.33.0
- name: docker.io/weaveworks/kured
  newName: acraksxoopss4bpzbr6.azurecr.io/live/weaveworks/kured
